name: Ubuntu
# Qt官方没有linux平台的x86包
on: 
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml' 
jobs:
  ubuntu:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.9.9
          cached: 'false'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev wget g++
      - name: install cmake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz
          tar zxf cmake-3.25.1.tar.gz
          chmod +x -R cmake-3.25.1-linux-x86_64/bin/
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          ./cmake-3.25.1-linux-x86_64/bin/cmake && cmake-3.25.1-linux-x86_64/bin/cmake install
